### ISSUE TITLE
有没有人遇到打开支付宝之后USB调试就会自动关闭？

### ISSUE THREAD

**Issue by VergLsm** [CivilNet/AntFarm#3]
有没有人遇到打开支付宝之后USB调试就会自动关闭？

**Comment by MrQcc** [comment]
> 有没有人遇到打开支付宝之后USB调试就会自动关闭？

魅族手机要在手机管家里面关闭flyme支付保护

**Comment by MrQcc** [comment]
> 有没有人遇到打开支付宝之后USB调试就会自动关闭？

@VergLsm flyme系统需要在安全管家关闭flyme支付保护

**Comment by VergLsm** [comment]
@MrQcc 好的，谢谢，顺便问一下现在这个项目还好用吗？

**Comment by MrQcc** [comment]
> @MrQcc 好的，谢谢，顺便问一下现在这个项目还好用吗？

@VergLsm 我试了一下，运行报错了，也试过其他的一些方式，太极magisk安装森林&庄园插件，这种方式应该是比较好的，可惜也不行

**Comment by VergLsm** [comment]
@MrQcc 推荐一下这个[https://github.com/SuperMonster003/Auto.js_Projects](url)

**Comment by MrQcc** [comment]
> @MrQcc 推荐一下这个[https://github.com/SuperMonster003/Auto.js_Projects](url)

@VergLsm 好的，有空看一下

**Comment by gemfield** [comment]
@VergLsm 功能正常，由于不同手机的分辨率和字体大小不同，你可能需要重新注册一套模板

**Comment by MrQcc** [comment]
@VergLsm 昨天晚上又试了下，可以跑起来。之前我遇到的问题是adb截图以后文件打开损坏，查了一下，说是Windows会自动把\n 替换为\r\n，然后我在截图之后重新读取文件替换再写回就可以运行了
@gemfield 跑了一夜功能正常，希望后续庄园能加入使用加速卡的功能

**Comment by gemfield** [comment]
@MrQcc 最新的commit已经包含了蚂蚁庄园加速卡功能。
